### ISSUE TITLE
Fabric 1.19.2 / Last update is not compatible anymore

### ISSUE THREAD

**Issue by suerion** [oskardotglobal/gottagofast-fabric#3]
Hey, the last update from today, let 1.19.2 not load anymore.

```
[20:28:47] [main/INFO]: Fix: add [], remove [], replace [[gottagofast 1.0.2] -> add:gottagofast 1 ([(-Ôê×,Ôê×)])]
[20:28:47] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Replace mod 'Gotta Go Fast!' (gottagofast) 1.0.2 with any version that is compatible with:
                 - minecraft 1.19.2
Unmet dependency listing:
         - Mod 'Gotta Go Fast!' (gottagofast) 1.0.2 requires version 1.19.3 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.19.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.19.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19.2-loader.0.14.19-launcher.0.11.2.jar:0.11.2]
```

**Comment by oskardotglobal** [comment]
Woops, the information on modrinth, the release page and curseforge is wrong. The latest version is only compatible with 1.19.3 + 4. I might make a 1.19.x version later, however, you can just stay on the older version. There are no new features / bugfixes in the latest release, you can just stay on the older version.
